### ISSUE TITLE
Lỗi force close ứng dụng đồng hồ khi tắt các mục báo thức hàng ngày

### ISSUE THREAD

**Issue by silversandxx** [Belmont-Gabriel/MIUI-12-XML-Vietnamese#10]
Xin chào,

Tôi đang sử dụng phiên bản miui 12 stable và miui 12.5 dev mỡi nhất và gặp 1 vấn đề mà tôi nghĩ là do gói ngôn ngữ

Khi tôi thử tắt mục báo thức hàng ngày bất kỳ thì ngay lập tức ứng dụng đồng hồ bị tắt (bình thường sẽ hiện lên 1 bảng hỏi có muốn tắt báo thức này trong ngày hay tắt hẳn)

Tuy nhiên, khi tôi thử tắt báo thức 1 lần thì không bị lỗi này

Tôi đã thử chuyển qua ngôn ngữ khác và không gặp lỗi

Tôi nghĩ nên report nó cho bạn để kiểm tra lại

https://user-images.githubusercontent.com/81069372/111897232-6c5dc200-8a51-11eb-8d65-9f34a0a74485.mp4

https://user-images.githubusercontent.com/81069372/111897235-7089df80-8a51-11eb-9334-4704e416eff2.mp4

**Comment by trantuananh1996** [comment]
Khi bị FC có cái bảng hiện lên, bạn bấm Xem chi tiết rồi chụp giúp mình nhé

**Comment by silversandxx** [comment]
[New Text Document.txt](https://github.com/Belmont-Gabriel/MIUI-12-XML-Vietnamese/files/6216902/New.Text.Document.txt)
Nó khá dài nên tôi sẽ gửi bạn file txt nhé

**Comment by minbaby01** [comment]
Same. Bản 12.0.6 eu poco m3 vẫn dính, để hàng ngày là bị crash 
`java.lang.IllegalArgumentException: no any time date
	at miuix.pickerwidget.date.DateUtils.getTimePatternResId(Unknown Source:199)
	at miuix.pickerwidget.date.DateUtils.formatDateTime(Unknown Source:91)
	at miuix.pickerwidget.date.DateUtils.formatDateTime(Unknown Source:15)
	at com.android.deskclock.util.Util.getSkipDateString(Unknown Source:60)
	at com.android.deskclock.alarm.AlarmClockFragment.showRepeatAlarmTurnOffDialog(Unknown Source:25)
	at com.android.deskclock.alarm.AlarmClockFragment.access$1200(Unknown Source:0)
	at com.android.deskclock.alarm.AlarmClockFragment$8.onCheckedChanged(Unknown Source:20)
	at com.android.deskclock.alarm.AlarmAdapter$5.onCheckedChanged(Unknown Source:32)
	at miuix.slidingwidget.widget.SlidingButtonHelper.notifyCheckedChangeListener(Unknown Source:14)
	at miuix.slidingwidget.widget.SlidingButtonHelper.animateToState(Unknown Source:16)
	at miuix.slidingwidget.widget.SlidingButtonHelper.animateToggle(Unknown Source:8)
	at miuix.slidingwidget.widget.SlidingButtonHelper.onTouchEvent(Unknown Source:128)
	at miuix.slidingwidget.widget.SlidingButton.onTouchEvent(Unknown Source:12)
	at android.view.View.dispatchTouchEvent(Unknown Source:97)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(Unknown Source:58)
	at android.view.ViewGroup.dispatchTouchEvent(Unknown Source:547)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(Unknown Source:58)
	at android.view.ViewGroup.dispatchTouchEvent(Unknown Source:547)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(Unknown Source:58)
	at android.view.ViewGroup.dispatchTouchEvent(Unknown Source:547)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(Unknown Source:58)
	at android.view.ViewGroup.dispatchTouchEvent(Unknown Source:547)
	at miuix.springback.view.SpringBackLayout.dispatchTouchEvent(Unknown Source:23)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(Unknown Source:58)
	at android.view.ViewGroup.dispatchTouchEvent(Unknown Source:547)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(Unknown Source:58)
	at android.view.ViewGroup.dispatchTouchEvent(Unknown Source:547)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(Unknown Source:58)
	at android.view.ViewGroup.dispatchTouchEvent(Unknown Source:547)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(Unknown Source:58)
	at android.view.ViewGroup.dispatchTouchEvent(Unknown Source:547)
	at miuix.springback.view.SpringBackLayout.dispatchTouchEvent(Unknown Source:23)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(Unknown Source:58)
	at android.view.ViewGroup.dispatchTouchEvent(Unknown Source:547)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(Unknown Source:58)
	at android.view.ViewGroup.dispatchTouchEvent(Unknown Source:547)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(Unknown Source:58)
	at android.view.ViewGroup.dispatchTouchEvent(Unknown Source:547)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(Unknown Source:58)
	at android.view.ViewGroup.dispatchTouchEvent(Unknown Source:547)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(Unknown Source:58)
	at android.view.ViewGroup.dispatchTouchEvent(Unknown Source:547)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(Unknown Source:58)
	at android.view.ViewGroup.dispatchTouchEvent(Unknown Source:547)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(Unknown Source:0)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(Unknown Source:2)
	at android.app.Activity.dispatchTouchEvent(Unknown Source:13)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(Unknown Source:2)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(Unknown Source:20)
	at android.view.View.dispatchPointerEvent(Unknown Source:9)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(Unknown Source:25)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(Unknown Source:115)
	at android.view.ViewRootImpl$InputStage.deliver(Unknown Source:21)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(Unknown Source:4)
	at android.view.ViewRootImpl$InputStage.forward(Unknown Source:0)
	at android.view.ViewRootImpl$AsyncInputStage.forward(Unknown Source:10)
	at android.view.ViewRootImpl$InputStage.apply(Unknown Source:2)
	at android.view.ViewRootImpl$AsyncInputStage.apply(Unknown Source:7)
	at android.view.ViewRootImpl$InputStage.deliver(Unknown Source:25)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(Unknown Source:4)
	at android.view.ViewRootImpl$InputStage.forward(Unknown Source:0)
	at android.view.ViewRootImpl$InputStage.apply(Unknown Source:2)
	at android.view.ViewRootImpl$InputStage.deliver(Unknown Source:25)
	at android.view.ViewRootImpl.deliverInputEvent(Unknown Source:63)
	at android.view.ViewRootImpl.doProcessInputEvents(Unknown Source:69)
	at android.view.ViewRootImpl.enqueueInputEvent(Unknown Source:34)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(Unknown Source:65)
	at android.view.InputEventReceiver.dispatchInputEvent(Unknown Source:25)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(Unknown Source:17)
	at android.os.Looper.loop(Unknown Source:65)
	at android.app.ActivityThread.main(Unknown Source:101)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:275)
 `

**Comment by trantuananh1996** [comment]
> Same. Bản 12.0.6 eu poco m3 vẫn dính, để hàng ngày là bị crash
Bạn trích file DeskClock.apk của mình ra rồi gửi giúp mình nhé

**Comment by minbaby01** [comment]
https://drive.google.com/file/d/10VquR_MSM-K7XbrWOUA2yq43hBBxgRNC/view?usp=drivesdk
Đây này

**Comment by trantuananh1996** [comment]
> https://drive.google.com/file/d/10VquR_MSM-K7XbrWOUA2yq43hBBxgRNC/view?usp=drivesdk
> Đây này

Oke thanks bạn để mình check xem

**Comment by trantuananh1996** [comment]
> https://drive.google.com/file/d/10VquR_MSM-K7XbrWOUA2yq43hBBxgRNC/view?usp=drivesdk
> Đây này

Bản 12.0.6 của M3 up ngày 21/3, bạn thử tìm bản mới hơn xem còn bị ko nhé. Cái này do xiaomi nó sửa code, mình vẫn chưa tìm thấy nó mò đến đâu

**Comment by trantuananh1996** [comment]
Hi @silversandxx @minbaby01 , các bản mới gần đây còn bị crash ko bạn?

**Comment by minbaby01** [comment]
M3 dính lỗi brick ko dám up, thấy up mỗi bảo mật nên thôi 😂😂

**Comment by trantuananh1996** [comment]
> M3 dính lỗi brick ko dám up, thấy up mỗi bảo mật nên thôi 😂😂

Từ hôm báo bug đến h chưa up bản nào mới hơn à 😂

**Comment by minbaby01** [comment]
> > M3 dính lỗi brick ko dám up, thấy up mỗi bảo mật nên thôi 😂😂
> 
> Từ hôm báo bug đến h chưa up bản nào mới hơn à 😂

Từ lúc cmt đến giờ mới đc ra bản up mới từ tuần trước. Con ghẻ thế thôi, cái này phải hỏi ae redmi, poco ko dám lên tiếng

**Comment by trantuananh1996** [comment]
Mình check bản mới nhất thì hết lỗi rồi đó
